import Form from "@/components/form";
import Logo from "@/components/logo";
import Head from "next/head";
import Link from "next/link";

export default function Inschrijven() {
  return (
    <>
      <Head>
        <title>WZV Zwemkamp - Inschrijven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-xl mx-auto px-4 pt-8">
        <div className="flex items-center mb-8">
          <Logo className="h-32" />
        </div>
        <Form />
      </main>
    </>
  );
}
