import {Formik} from "formik";
import Head from "next/head";
import Link from "next/link";

export default function Inschrijven() {
  return (
    <>
      <Head>
        <title>WZV Zwemkamp - Inschrijven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen flex flex-col justify-center items-center'>
        <h1>Schrijf je nu in</h1>

        <Formik initialValues={{ name: null, }}
          {props => (
            <input type='text' />
          )}
        </Formik>
      </main>
    </>
  )
}
